### ISSUE TITLE
Use `CryptoKey` for TLS keys

### ISSUE THREAD

**Issue by lucacasonato** [jasnell/sockets-api#1]
Currently this proposal uses a plain Uint8Array for TLS certificates and keys. This means that this spec needs to define how the keys are interpreted and parsed. There is already a different part of the web platform that specifies parsing of crypto keys: WebCrypto. What if we use the `CryptoKey` object from WebCrypto to represent keys?

These support RSA and ECDSA keys, which is exactly what we would need.

**Comment by jasnell** [comment]
+1... absolutely agree. Representing certs is also an issue here, tho. We have an `X509Certificate` object in Node.js but it would be better if there were a common API. But yes, using `CryptoKey` makes perfect sense for this part.

**Comment by jasnell** [comment]
see https://github.com/jasnell/sockets-api/pull/9 for an update

**Comment by jasnell** [comment]
Handled in #9
