### ISSUE TITLE
Go all in on WHATWG streams

### ISSUE THREAD

**Issue by lucacasonato** [jasnell/sockets-api#3]
Instead of providing a `body` on creation, writing to the socket should happen via a WritableStream. This would be achieved by implementing the [`GenericTransformStream`](https://streams.spec.whatwg.org/#generictransformstream) mixin for `Socket`.

Why? `GenericTransformStream` is the new standard browser primitive for streaming APIs. It is used by many shipping and in progress APIs. It would be good to align.

- [`TextEncoderStream`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoderStream) (shipped)
- [`TextDecoderStream`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoderStream) (shipped)
- [`CompressionStream`](https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream) (shipped)
- [`DecompressionStream`](https://developer.mozilla.org/en-US/docs/Web/API/DecompressionStream) (shipped)
- [`WebSocketStreamConnection`](https://github.com/ricea/websocketstream-explainer/blob/master/README.md) (in origin trial)
- [`WebTransportDatagramDuplexStream`](https://w3c.github.io/webtransport/#webtransportdatagramduplexstream) (being specified)
- [`WebTransportBidirectionalStream`](https://w3c.github.io/webtransport/#webtransportbidirectionalstream) (being specified)

Using WHATWG streams provide some nice benefits that some other options do not:
- Backpressure: an event based API does not provide backpressure
- Externally writable: an async iterator API based writer can not be written externally written to. A `WritableStream` has a `.write` method, but an async iterator can only be created by manually implementing the async iteration protocol or using a generator, both of which don't make it easy to create an iterator, and then write to it.
- Easy piping and interop with existing APIs:
   ```js
   outgoingChunks
      .pipeThrough(new TextEncoderStream())
      .pipeThrough(new CompressionStream("gzip"))
      .pipeTo(socket.writable);

   const incomingChunks = socket.readable
      .pipeThrough(new DecompressionStream("gzip"))
      .pipeThrough(new TextDecoderStream());
   ```

Once concern that will be brought up is that WHATWG streams are slower than some alternatives. While this can be the case, in general this is not usually a bottleneck: the Deno HTTP server builds entirely on the `fetch` API that uses `ReadableStream` and `WritableStream`, but still has a 5-10% lead over the Node HTTP server that builds on events. If it is decided that this is really an issue, we could always subclass `ReadableStream` and `WritableStream` and add `read(buf: Uint8Array): Promise<number>` and `write(buf: Uint8Array): Promise<number>` methods respectively for low level reading and writing. This would still support backpressure.

I'd say the benefits outweigh the downsides for using WHATWG streams.

**Comment by jasnell** [comment]
For the sake of discussion.... A bit of context on the why for the current design...

It's not entirely about the performance of the streams API itself, it's also about optimizing the flow of data at the underlying layers also, and for enabling support of features like 0RTT fast starts (when a protocol supports it). Passing in a payload source (the `body`) either in the constructor or the `respondWith` allows us, in various cases, to reduce the latency between when a connection is established and when the flow of data can begin. In the case of QUIC, for instance, it allows us to more efficiently support 0RTT fast-starts, where streams can be opened during the TLS handshake. It also gives us more options for data sources. That said, we could also optimize by deferring the start of the connection/handshake until the flow of data actually starts but there are other advantages to the current design.

The current design, for instance, allows us to completely bypass using a streams API entirely when all of the data can be read and transmitted more efficiently at a native layer, which is the case when using `Blob` or `ArrayBuffer` sources, or in Node.js, when using a `FileHandle` object. In each of these cases, using `stream.writable` just adds overhead that can be avoided.

```js
// In Node.js, fs.promises.open returns a FileHandle, which allows data to be
// read efficiently entirely at the native layer, completely bypassing the streams
// APIs, and allowing the flow of data to start as soon as the connection is established.
const { open } = require('fs/promises');
cons socket = new Socket({ body: open('some_file') });
```

With this approach, as soon as the connection is established the file data can start to be transmitted without incurring the additional latency of calling back out to the JS layer at all. The performance boost is significant.

Also, with the current design, it's possible to achieve the same basic pattern you illustrate:

```js
const socket = new Socket({
  body: outgoingChunks
          .pipeThrough(new TextEncoderStream())
          .pipeThrough(new CompressionStream("gzip"));
  }
});
```

If the use of the socket needs to be more conversational, that's possible also...

```js
const t = new TransformStream();
cons socket = new Socket({ body: t.readable });
const reader = socket.stream().getReader();
const writer = t.writable.getWriter();

await chunk = reader.read();
await writer.write('...');
```

In the case where there is not going to be an outbound flow of data, or when that outbound data is already known, making that information available as soon as possible when the `Socket` is created allows us to optimize a number of cases.

I'm certainly not opposed to exposing a `WritableStream` off the `Socket`, and I agree with the point about API consistency, but I'd like us to try to handle:

1. Supporting fixed data sources like strings, `Blob`, `ArrayBufferView`s, purely native layer data sources like node.js' `FileHandle`, etc where use of a stream API just isn't necessary.
2. Supporting 0RTT fast starts when supported by the protocol.
3. Supporting as early as possible indication of whether an outbound payload is even going to be provided (e.g. not having to wait until `socket.writable.close()` is explicitly called when we know already that we're not going to send any data.

**Comment by uasan** [comment]
I like`{ body: t.readable }` - it is an interface instead of `WritableStreamBYOB` (which unfortunately do not exist in the specification).

But this does not exclude the need for the `Socket` class to implement the interface `GenericTransformStream`.
I wish there was a `{ body: t.readable }` and mixin `GenericTransformStream`.

Most high-level protocols (Postgres, Redis, etc.) have an authorization mechanism, it is convenient to implement it in the body (static binary message), after successful authorization, use `writer.write()` from the mixin `GenericTransformStream`

**Comment by jasnell** [comment]
Updating the proposal to support *both*. If `body` is provided in the init, then it will be used as soon as possible when the connection is established. The `socket.writable` will be `locked` in that case so `socket.writable.getWriter()` will fail. Consider it a shortcut for early binding the `socket.writable`. However, if `body` is not provided, then `socket.writable` is used to write outbound data on the socket.

**Comment by jasnell** [comment]
see https://github.com/jasnell/sockets-api/pull/9 for an update

**Comment by jasnell** [comment]
Handled in #9
