### ISSUE TITLE
setting timeouts

### ISSUE THREAD

**Issue by bmeck** [jasnell/sockets-api#5]
for sockets left open for connection costs it would be good to be able to reset the timeout to a long duration when inactive and short duration when active. I think leaving it up to the user to change this duration is fine. also, this is likely a non-issue for most use cases so leaving it out is also fine if it adds complexity/perf issues for the common case.

**Comment by jasnell** [comment]
Agreed. Working that into an update PR now

**Comment by jasnell** [comment]
see https://github.com/jasnell/sockets-api/pull/9 for an update

**Comment by jasnell** [comment]
Handled in #9
